source 'https://rubygems.org'

gem 'rails', '4.2.3'

gem 'sqlite3'

gem 'prawn'
gem 'prawn-table'
gem 'combine_pdf'
gem 'refile', github: 'refile/refile', require: 'refile/rails'

group :test do
  gem 'minitest'
end